# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './NewEntry.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(725, 685)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 709, 297))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_Name = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Name.setObjectName("lbl_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_Name)
        self.Le_Name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.Le_Name.setClearButtonEnabled(False)
        self.Le_Name.setObjectName("Le_Name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Le_Name)
        self.lbl_Kategorie = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Kategorie.setObjectName("lbl_Kategorie")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_Kategorie)
        self.Le_Kategorie = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.Le_Kategorie.setObjectName("Le_Kategorie")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Le_Kategorie)
        self.lbl_Lagerplatz = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Lagerplatz.setObjectName("lbl_Lagerplatz")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_Lagerplatz)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_mainLocation = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_mainLocation.sizePolicy().hasHeightForWidth())
        self.cb_mainLocation.setSizePolicy(sizePolicy)
        self.cb_mainLocation.setObjectName("cb_mainLocation")
        self.horizontalLayout_3.addWidget(self.cb_mainLocation)
        self.cb_subLocation = QtWidgets.QComboBox(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_subLocation.sizePolicy().hasHeightForWidth())
        self.cb_subLocation.setSizePolicy(sizePolicy)
        self.cb_subLocation.setObjectName("cb_subLocation")
        self.horizontalLayout_3.addWidget(self.cb_subLocation)
        self.pb_addLocation = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_addLocation.sizePolicy().hasHeightForWidth())
        self.pb_addLocation.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/emblem-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_addLocation.setIcon(icon)
        self.pb_addLocation.setIconSize(QtCore.QSize(16, 16))
        self.pb_addLocation.setFlat(True)
        self.pb_addLocation.setObjectName("pb_addLocation")
        self.horizontalLayout_3.addWidget(self.pb_addLocation)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.lbl_Anzahl = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Anzahl.setObjectName("lbl_Anzahl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_Anzahl)
        self.Le_Anzahl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.Le_Anzahl.setObjectName("Le_Anzahl")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Le_Anzahl)
        self.lbl_minMenge = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_minMenge.setObjectName("lbl_minMenge")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_minMenge)
        self.le_minMenge = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_minMenge.setObjectName("le_minMenge")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_minMenge)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_mhd = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_mhd.setObjectName("lbl_mhd")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_mhd)
        self.dE_MHD = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_3)
        self.dE_MHD.setObjectName("dE_MHD")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dE_MHD)
        self.lbl_Gewicht = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Gewicht.setObjectName("lbl_Gewicht")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_Gewicht)
        self.le_Menge = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_Menge.setObjectName("le_Menge")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.le_Menge)
        self.lbl_Portionen = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Portionen.setObjectName("lbl_Portionen")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_Portionen)
        self.le_portionen = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_portionen.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.le_portionen.setObjectName("le_portionen")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.le_portionen)
        self.lbl_Kalorien = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.lbl_Kalorien.setObjectName("lbl_Kalorien")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_Kalorien)
        self.le_Kalorien = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.le_Kalorien.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.le_Kalorien.setMaxLength(5)
        self.le_Kalorien.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_Kalorien.setObjectName("le_Kalorien")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_Kalorien)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label)
        self.te_notes = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_3)
        self.te_notes.setObjectName("te_notes")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.te_notes)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pB_Abbrechen = QtWidgets.QPushButton(Dialog)
        self.pB_Abbrechen.setObjectName("pB_Abbrechen")
        self.horizontalLayout.addWidget(self.pB_Abbrechen)
        self.PB_createItem = QtWidgets.QPushButton(Dialog)
        self.PB_createItem.setObjectName("PB_createItem")
        self.horizontalLayout.addWidget(self.PB_createItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_StatusText = QtWidgets.QLabel(Dialog)
        self.lbl_StatusText.setText("")
        self.lbl_StatusText.setObjectName("lbl_StatusText")
        self.verticalLayout.addWidget(self.lbl_StatusText)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Neuer Eintrag"))
        self.lbl_Name.setText(_translate("Dialog", "Name:"))
        self.Le_Name.setToolTip(_translate("Dialog", "Name des Produkts"))
        self.Le_Name.setStatusTip(_translate("Dialog", "Bitte den Namen des Produkts eingeben"))
        self.Le_Name.setPlaceholderText(_translate("Dialog", "Name"))
        self.lbl_Kategorie.setText(_translate("Dialog", "Kategorie:"))
        self.Le_Kategorie.setPlaceholderText(_translate("Dialog", "Kategorie"))
        self.lbl_Lagerplatz.setText(_translate("Dialog", "Lagerplatz:"))
        self.lbl_Anzahl.setText(_translate("Dialog", "Anzahl:"))
        self.Le_Anzahl.setPlaceholderText(_translate("Dialog", "Anzahl"))
        self.lbl_minMenge.setText(_translate("Dialog", "min. Menge:"))
        self.le_minMenge.setToolTip(_translate("Dialog", "die Menge die immer vorrätig  sein sollte"))
        self.le_minMenge.setPlaceholderText(_translate("Dialog", "mindest Menge"))
        self.lbl_mhd.setText(_translate("Dialog", "MHD:"))
        self.lbl_Gewicht.setText(_translate("Dialog", "Menge:"))
        self.le_Menge.setPlaceholderText(_translate("Dialog", "Inhaltsmenge"))
        self.lbl_Portionen.setText(_translate("Dialog", "Portionen:"))
        self.le_portionen.setInputMask(_translate("Dialog", "999"))
        self.le_portionen.setPlaceholderText(_translate("Dialog", "Portionen"))
        self.lbl_Kalorien.setText(_translate("Dialog", "kcal/Portion:"))
        self.le_Kalorien.setInputMask(_translate("Dialog", "99999"))
        self.le_Kalorien.setPlaceholderText(_translate("Dialog", "Kalorien pro Portion"))
        self.label.setText(_translate("Dialog", "Notizen"))
        self.te_notes.setPlaceholderText(_translate("Dialog", "Notizen/Beschreibung"))
        self.pB_Abbrechen.setText(_translate("Dialog", "Schließen"))
        self.PB_createItem.setToolTip(_translate("Dialog", "Neues Item erstellen"))
        self.PB_createItem.setText(_translate("Dialog", "Item anlegen"))
from ui import icons_rc
